// Generated by MS2Porter
const version = '1.0.4';

let getUser, getMembers, getGuildId;
let interval;

const run = () => {
  let popout = document.getElementsByClassName('userPopout-2j1gM4')[0];
  
  if (!popout) return;
  if (popout.classList.contains('more-info-added')) return;

  let user = getUser.getUser(getMembers.getMembers(getGuildId.getGuildId()).find((x) => getUser.getUser(x.userId).username === popout.ariaLabel).userId);

  let toCloneEl = popout.getElementsByClassName('headerTagWithNickname-1U8zZH')[0];

  if (!toCloneEl) {
    let headerEl = popout.getElementsByClassName('headerTagNoNickname-3tGHj6o')[0];
    
    let parentEl = document.createElement('div');

    headerEl.parentElement.appendChild(parentEl);

    parentEl.outerHTML = `<div class="headerTagWithNickname-1U8zZH headerTag-3GXZkV nameTag-H6kSJ0" style="flex: 1 1 auto;"><span class="username-3JLfHz headerTagUsernameBase-XYisdh"></span></div>`;

    toCloneEl = popout.getElementsByClassName('headerTagWithNickname-1U8zZH')[0];

    headerEl.parentElement.style.flexDirection = 'column';
  }

  toCloneEl.parentElement.style.flexDirection = 'column';

  let el = toCloneEl.cloneNode(false);

  el.textContent = `Created On: ${user.createdAt.toDateString().split(' ').slice(1).join(' ')}`;

  toCloneEl.parentElement.appendChild(el);

  popout.classList.add('more-info-added');
};

export default {
goosemodHandlers: {
  onImport: async function () {
    getUser = goosemodScope.webpackModules.findByPropsAll('getUser')[1];
    getMembers = goosemodScope.webpackModules.findByProps('getNick');
    getGuildId = goosemodScope.webpackModules.findByPropsAll('getGuildId')[1];

    interval = setInterval(run, 500);
  },

  onLoadingFinished: async function () {
  },

  onRemove: async function () {
    clearInterval(interval);
  },

  logRegionColor: 'darkred',



}
};
