// Generated by MS2Porter
const version = '1.0.1';

let el;

const css = `.groupStart-3Mlgv1:not(.message-2CShn3) {
  display: none;
}`;

export default {
goosemodHandlers: {
  onImport: async function () {
    el = document.createElement('style');

    document.head.appendChild(el);

    el.appendChild(document.createTextNode(css));
  },

  onRemove: async function () {
    el.remove();
  },



}
};
